# Generated by Django 4.1.7 on 2023-08-03 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_customer_orders_till_now_customer_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
