# Generated by Django 4.1.7 on 2023-08-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0003_remove_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_token',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
