# Generated by Django 4.1.7 on 2023-07-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_sale',
            field=models.BigIntegerField(null=True),
        ),
    ]
