# Generated by Django 4.1.7 on 2023-07-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_orders_car_adress_orders_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='no_of_items',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
