# Generated by Django 4.1.7 on 2023-07-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_orders_no_of_items_orders_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AlterField(
            model_name='orders',
            name='total_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
