# Generated by Django 4.1.7 on 2023-07-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_product_desc_remove_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='car_adress',
        ),
    ]
