# Generated by Django 4.1.7 on 2023-07-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_reviews_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Product',
        ),
    ]
