# Generated by Django 4.1.7 on 2023-07-28 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
    ]
