# Generated by Django 4.1.7 on 2023-07-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_status_order_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_tracking',
            name='dlivery_status',
        ),
        migrations.DeleteModel(
            name='status',
        ),
        migrations.AddField(
            model_name='order_tracking',
            name='dlivery_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
