# Generated by Django 4.1.7 on 2023-07-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_order_tracking_product_order_tracking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tracking_id_assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order_tracking',
            name='tracking_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.tracking_id_assignment'),
        ),
    ]
