# Generated by Django 4.1.7 on 2023-07-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_tracking_id_assignment_order_tracking_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_tracking',
            name='tracking_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='tracking_id_assignment',
        ),
    ]
