# Generated by Django 4.1.7 on 2023-07-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_order_tracking_tracking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='tracking_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
