# Generated by Django 4.1.7 on 2023-07-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_orders_tracking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='order_tracking',
            name='dlivery_status',
        ),
        migrations.AddField(
            model_name='order_tracking',
            name='dlivery_status',
            field=models.ManyToManyField(max_length=200, null=True, to='base.status'),
        ),
    ]
