# Generated by Django 4.1.7 on 2023-08-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_product_created_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tracking_id',
            field=models.UUIDField(null=True),
        ),
    ]
