# Generated by Django 4.1.7 on 2023-08-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_orders_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='tracking_id',
        ),
        migrations.AlterField(
            model_name='order_tracking',
            name='dlivery_status',
            field=models.ManyToManyField(null=True, to='base.status'),
        ),
        migrations.AlterField(
            model_name='order_tracking',
            name='tracking_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
