# Generated by Django 4.1.7 on 2023-08-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_remove_orders_tracking_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
